#!/bin/bash

res=$(echo "1:Htop|2:Ping|3:Wifi" | rofi -sep "|" -dmenu -i -p 'Narzędzia ' "" -bw 0 -bc "#dc1900" -bg "#1e1e20" -fg "#e0d8d1" -hlbg "#1e1e20" -hlfg "#dc1900" -width 15 -hide-scrollbar -eh 4 -location 1 -yoffset 23 -padding 35 -opacity 100 -font "Awesome 10, SFNS Regular 10" -auto-select)

if [ $res = "1:Htop" ]; then
  terminator --command "htop"
fi
if [ $res = "2:Ping" ]; then
  terminator --command "ping 8.8.8.8"
fi
if [ $res = "3:Wifi" ]; then
  nm-applet
fi

exit 0
