#!/bin/bash

res=$(echo "1:Htop|2:Ping|3:Wifi" | rofi -sep "|" -dmenu -i -p 'Narzędzia ' "" -bw 0 -bc "#002b36" -bg "#002b36" -fg "#cb4b16" -hlbg "#002b36" -hlfg "#cb4b16" -width 15 -hide-scrollbar -eh 4  -padding 35 -opacity 100 -font "SFNS Regular 10" -auto-select)

if [ $res = "1:Htop" ]; then
  terminator --command "htop"
fi
if [ $res = "2:Ping" ]; then
  terminator --command "ping 8.8.8.8"
fi
if [ $res = "3:Wifi" ]; then
  nm-applet
fi

exit 0
